"""empty message

Revision ID: 9cb6e7919fe0
Revises: acdf99a5220e
Create Date: 2024-02-27 15:15:18.184573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb6e7919fe0'
down_revision = 'acdf99a5220e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultorios')
    # ### end Alembic commands ###
