"""empty message

Revision ID: acdf99a5220e
Revises: 5ed5e37fb9b5
Create Date: 2024-02-27 15:03:59.278762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acdf99a5220e'
down_revision = '5ed5e37fb9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('apellidos', sa.String(length=120), nullable=True),
    sa.Column('tipo_identificacion', sa.String(length=4), nullable=True),
    sa.Column('numero_identificacion', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('tipo_sangre', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('paciente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('apellidos', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('tipo_identificacion', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('numero_identificacion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('altura', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tipo_sangre', mysql.VARCHAR(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('pacientes')
    # ### end Alembic commands ###
